### ISSUE TITLE
Video description not working

### ISSUE THREAD

**Issue by ivanjokalov** [thistlecafe/cosmic-cat#127] opened 2023-03-26 18:50 UTC
### Type

Page Renderer

### Page URL

https://www.youtube.com/watch?v=aKKBvQLVUA8

### Branch

main

### Version

0.6.29

### A brief description

The descrition on videos is not showing

### Screenshots or videos

On this screen shot is the video and its description on vanilla youtube:
![Screenshot 2023-03-26 at 21-43-09 Джамайка и Тони Стораро - Най-добрата фирма](https://user-images.githubusercontent.com/77291455/227797326-9ac1fdc7-9b97-4098-915c-500035f259b4.png)
(I scrolled down a bit to show the dscrition)

On this screen shot is the video and its descrition on cosmic cat youtube:
![Screenshot 2023-03-26 at 21-41-55 Джамайка и Тони Стораро - Най-добрата фирма - YouTube](https://user-images.githubusercontent.com/77291455/227797351-48c3854e-e5e7-4886-9d16-cca4e3fe6590.png)

### Console output

[console-export-2023-3-26_21-40-31.txt](https://github.com/thistlecafe/cosmic-cat/files/11072686/console-export-2023-3-26_21-40-31.txt)

**Comment by ciulinuwu** [comment] 2023-03-30 18:05
Duplicate of #118

**Closed by ciulinuwu** 2023-03-30 18:05 UTC
