### ISSUE TITLE
video links don't go to videos

### ISSUE THREAD

**Issue by nope312** [thistlecafe/cosmic-cat#130] opened 2023-03-27 19:59 UTC
### Type

Page Renderer

### Page URL

https://www.youtube.com/watch/featured

### Branch

main

### Version

latest

### A brief description

almost all videos i go to bring me to https://www.youtube.com/watch/featured, with  iFrame player on or off it still doesn't work

### Screenshots or videos

![problemo](https://user-images.githubusercontent.com/65314830/228052657-bc03ecf9-233f-4e5e-ab22-976b3356412e.PNG)

### Console output

userscript.html?name=Cosmic%2520Cat.user.js&id=05680f71-8d23-430c-b642-4854cefff51d:5513 Storage.init storage has init.
userscript.html?name=Cosmic%2520Cat.user.js&id=05680f71-8d23-430c-b642-4854cefff51d:6331 Loaded page in:  -215 ms
general-web-content-script.js:1392 GeneralWebCS: init
general-web-content-script.js:1569 ScribleGeneralWebContentScript: Got window message MessageEvent
userscript.html?name=Cosmic%2520Cat.user.js&id=05680f71-8d23-430c-b642-4854cefff51d:4022 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.escapeHtml (userscript.html?name=Cosmic%2520Cat.user.js&id=05680f71-8d23-430c-b642-4854cefff51d:4022:18)
    at Object.metadata (userscript.html?name=Cosmic%2520Cat.user.js&id=05680f71-8d23-430c-b642-4854cefff51d:3265:66)
    at Object.Main (userscript.html?name=Cosmic%2520Cat.user.js&id=05680f71-8d23-430c-b642-4854cefff51d:3287:45)
    at userscript.html?name=Cosmic%2520Cat.user.js&id=05680f71-8d23-430c-b642-4854cefff51d:6056:117
featured:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
content.js:309 Unable to find the video player settings menu, annotation switch not injected
(anonymous) @ content.js:309
featured:1 The resource https://i.ytimg.com/generate_204 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for chrome-extension://lijhjhlnfifgoabbihoobnfapogkcjgk/content-scripts/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for https://www.youtube.com/s/desktop/688c82de/jsbin/custom-elements-es5-adapter.vflset/blaze-out/k8-opt/bin/third_party/javascript/custom_elements/fast-shim.js.sourcemap: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://www.youtube.com/s/desktop/688c82de/jsbin/webcomponents-sd.vflset/blaze-out/k8-opt/bin/third_party/javascript/polymer/v2/webcomponentsjs/webcomponents-sd.js.sourcemap: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://www.youtube.com/s/desktop/688c82de/jsbin/web-animations-next-lite.min.vflset/web-animations-next-lite.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
featured:1 The resource https://i.ytimg.com/generate_204 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

**Comment by Quentendo** [comment] 2023-03-28 02:52
does this when you use adblock, try using ublock origin instead or something

**Comment by ciulinuwu** [comment] 2023-03-30 17:58
Duplicate of #129

**Closed by ciulinuwu** 2023-03-30 17:58 UTC
